spring:
  application:
    name: demo

  web:
    servlet:
      context-path: /api

  datasource:
    url: jdbc:postgresql://localhost:5432/test1
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password: redispassword
#      timeout: 2000ms